@WeatherAPI_HostAddress = http://localhost:5167

GET {{WeatherAPI_HostAddress}}/weatherforecast/
Accept: application/json


### Test a Valid City Status Check
GET http://localhost:5167/api/weather/berlin
Accept: application/json
###
